[package]
name = "s3_view"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwasm = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
yew = { version = "0.21.0", features = ["csr"] }


[lib]
crate-type = ["cdylib"]
